### ISSUE TITLE
The user_groups API doesn't show the full list of available groups

### ISSUE THREAD

**Issue by lgiommi** [infn-datacloud/federation-registry#17]
Doing the GET to the user_groups endpoint the federation registry dos not show the full list of available groups

**Comment by giosava94** [comment]
When adding multiple providers, the current behavior is that the DB stores only the last received list of user groups. The correct behavior should be that it extends the list of the user groups instead of replacing it. 

We need to investigate if this is a problem rooted in the 'update' operation of the fed-reg or if it is an error in the feeder script.
